title: 我的文章分享
timezone: Asia/Shanghai
author: plutotree
email: plutotreetree@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am thinking about what to write...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plutotree.cn" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  plutotree

# 是否添加百度统计
baidu_analytics: 1
# 底部是否展示ICP备案信息
icp_footer: 1

# Build settings
permalink: /:year-:month-:day/:title.html 
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
