# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 我的文章分享
author: plutotree
email: plutotreetree@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am thinking about what to write...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plutotree.cn" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  plutotree

# 是否添加百度统计
baidu_analytics: 1
# 底部是否展示ICP备案信息
icp_footer: 1

# Build settings
permalink: /:year-:month-:day/:title.html 
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude: