name: Deploy Hugo to GitHub Pages
on:
  push:
    branches: [ "master" ] # 触发分支
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 包含主题子模块

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.145.0"
          extended: true # 启用 Extended 版本

      - name: Build
        run: hugo --minify --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: plutotree.me
          force_orphan: true

      - name: Upload Artifactia
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: algolia-index
          path: public/index.json

      # 使用 Algolia CLI 上传
      - name: Install Algolia CLI
        run: npm install -g @algolia/cli

      - name: Push Index to Algolia
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        run: |
          algolia objects import \
            --index-name index \
            --file public/index.json

      - name: Pushover Notification
        uses: umahmood/pushover-actions@v1.1.0
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: "pages Deploy Notification"
          message: ${{github.event.head_commit.message}}
